Repository epsagon/epsagon-node, pull requests merged in 2020-11, with the labels that each got.

#383 feat(setwarning): add setWarning method
  README.md
  src/event.js
  src/index.js
  src/tracer.js
Labels: size/M, status: ready

#384 fix(setWarning): add setWarning type declaration
  src/index.d.ts
Labels: size/XS

#385 feat(sql): collecting response data
  src/events/sql.js
  src/tracer.js
Labels: size/S

#388 feat(aws_sdk.js): support filter log events
  src/events/aws_sdk.js
Labels: size/M

#387 feat(fs): add node fs support
  README.md
  src/events/fs.js
Labels: size/M, status: ready

#389 feat(ec2): capture ec2 metadata
  src/containers/ec2.js
  src/patcher.js
  src/tracer.js
Labels: size/M

#373 feat(batch processing): traces queue + batch sending + byte size limit
  .gitignore
  examples/batch_example.js
  src/config.js
  src/consts.js
  src/index.d.ts
  src/trace_queue.js
  src/tracer.js
  test/unit_tests/events/ldapjs.js
  test/unit_tests/test_config.js
  test/unit_tests/test_trace_queue.js
Labels: size/XL, status: ready

#390 fix(batch-processing): post fix
  examples/batch_example.js
  src/trace_queue.js
Labels: size/S

#393 feat(config.js): add option to remove ignored keys
  README.md
  src/config.js
  src/events/aws_sdk.js
  src/events/http.js
  src/events/http2.js
  src/tracer.js
Labels: size/S
