Repository epsagon/epsagon-node, pull requests merged in 2020-10, with the labels that each got.

#369 fix(lambda.js): add custom timeout threshold
  README.md
  src/wrappers/lambda.js
Labels: size/XS

#370 feat(mongodb): add items count to mongodb event metadata
  src/events/mongodb.js
Labels: size/M

#371 fix(readme): fix labels docs
  README.md
Labels: size/XS

#374 feat(azure timeout): add default andd short timeout for azure requests
  src/containers/azure.js
Labels: size/XS

#375 feat(ignored-keys): write ignored keys and mask their value
  src/tracer.js
  test/unit_tests/test_tracer.js
Labels: size/M

#376 feat(pino.js): add trace id to pino logger
  README.md
  src/events/pino.js
  src/patcher.js
Labels: size/M

#377 feat(skip simple auth): skip simple auth requests
  .gitignore
  src/events/http.js
Labels: size/M

#378 feat(http): saving response/request body even if not json
  src/helpers/http.js
Labels: size/S

#381 fix(consts): add lambda main keys to strong id keys array
  src/consts.js
Labels: size/XS

#379 feat(tracer): trimming exceptions when tracer is more than max size
  src/tracer.js
Labels: size/M

#380 feat(sqs): supporting multiple sqs messages for lambda trigger
  src/triggers/aws_lambda.js
  src/utils.js
Labels: size/M
