Repository epsagon/epsagon-node, pull requests merged in 2020-06, with the labels that each got.

#294 feat(node): connect node wrapper to step functions flow by env vars
  README.md
  src/wrappers/node.js
Labels: size/S

#296 fix(http.js): fix non function in got http
  src/events/http.js
Labels: size/XS

#297 fix(http.js): allow disabling trace id propagation in http
  README.md
  src/events/http.js
Labels: size/XS

#298 Fix/fix stepfunctions with ecs/ep 0000
  README.md
  src/wrappers/node.js
Labels: size/S

#299 fix(config.js): add EPSAGON_COLLECTOR_URL env var
  README.md
  src/config.js
Labels: size/XS

#300 fix(winston.js): add more debug prints
  src/consts.js
  src/events/winston.js
  src/tracer.js
Labels: size/XS

#301 fix(mongodb): adding verbose logging
  src/events/mongodb.js
Labels: size/XS

#302 feat(node): adding trace_id to node_wrapper
  src/events/mongodb.js
  src/wrappers/node.js
Labels: size/XS

#303 fix(tracer): keeping labels in runner metadata
  src/tracer.js
Labels: size/S

#304 fix(mongodb): improving mongodb connectionId parsing + verbose logging
  package.json
  src/events/mongodb.js
Labels: size/M

#305 fix(winston-cw): adding tags even if init is inside handler execution
  src/tracer.js
Labels: size/S

#306 feat(winston-cw): adding region and account id to winston cloudwatch
  src/events/winston_cloudwatch.js
Labels: size/M

#308 fix(tracer.js): moving ignored keys handling order
  src/tracer.js
Labels: size/S

#309 feat(winston-cw): collecting multiple destinations
  src/events/winston_cloudwatch.js
  src/tracer.js
Labels: size/M

#310 fix(azure_sdk): update cosmos db event name
  src/events/azure_sdk.js
Labels: size/XS

#311 feat(amqplib.js): add support fot amqplib
  README.md
  package-lock.json
  package.json
  src/events/amqplib.js
  src/patcher.js
Labels: size/L

#312 Azure fix ep 000
  src/events/azure_sdk.js
Labels: size/XS

#313 fix(package.json): remove amqplib from deps
  package-lock.json
  package.json
Labels: size/XS

#317 fix(http.js): update uuid dependency
  package-lock.json
  package.json
  src/helpers/http.js
Labels: size/S
