Repository epsagon/epsagon-node, pull requests merged in 2020-07, with the labels that each got.

#318 [EP-3515]: Fixing duplicate JSONify
  src/triggers/aws_lambda.js
  src/wrappers/node.js
Labels: size/S

#319 fix(aws_lambda): Fixing duplicate JSONify
  README.md
Labels: size/XS

#320 fix(http.js): update got module handling
  src/events/http.js
Labels: size/M

#321 feat(azure_detection): support azure vendor detection
  src/consts.js
  src/containers/azure.js
  src/tracer.js
Labels: size/M

#323 feat(ioredis.js): add support for ioredis
  README.md
  src/events/ioredis.js
  src/patcher.js
Labels: size/L

#324 fix(index.js): expose http helpers
  src/index.js
Labels: size/XS

#325 docs(README): update link
  README.md
Labels: size/XS

#326 feat(ecs): extracting ecs account id from ecs metadata
  src/containers/ecs.js
  src/tracer.js
Labels: size/S

#327 fix(aws_lambda.js): fix sqs trigger
  package-lock.json
  src/triggers/aws_lambda.js
Labels: size/S

#328 fix(package.json): update packages
  package-lock.json
  package.json
Labels: size/XS

#329 feat(aws_lambda.js): add support for API Gateway WebSocket
  src/triggers/aws_lambda.js
Labels: size/S

#331 fix(amqplib.js): add message size to metadata
  src/events/amqplib.js
Labels: size/XS

#333 fix(readme): update auto tracing
  README.md
Labels: size/XS

#334 fix(http.js): add epsagon header in case no headers set
  src/events/http.js
Labels: size/XS

#332 feat(lables): support labels inside init
  .travis.yml
  README.md
  scripts/publish_layers.sh
  src/config.js
  src/tracer.js
Labels: size/M

#335 feat(azure-tags): format azure tags to json
  src/containers/azure.js
Labels: size/S

#336 feat(readme): update docs
  README.md
Labels: size/XS

#338 fix(tracer): fix sampling on lambda
  src/config.js
  src/consts.js
  src/trace_object.js
  src/tracer.js
  test/unit_tests/wrappers/test_openwhisk_traces.js
Labels: size/S

#337 fix(utils.js): disable events in lambda env
  src/config.js
  src/tracer.js
  src/utils.js
Labels: size/S
