Repository epsagon/epsagon-node, pull requests merged in 2020-09, with the labels that each got.

#351 fix(aws_lambda.js): add default op to websocket trigger
  src/triggers/aws_lambda.js
Labels: size/XS

#352 feat(amqp.js): add support for amqp
  README.md
  package-lock.json
  package.json
  src/events/amqp.js
  src/patcher.js
Labels: size/M

#353 feat(aws_sdk.js): support EventBridge
  src/events/aws_sdk.js
  src/triggers/aws_lambda.js
Labels: size/M

#354 feat(kafka-node.js): support kafka-node
  README.md
  src/events/kafka-node.js
  src/patcher.js
Labels: size/L

#355 fix(aws_batch.js): fix JSON handling of AWS Batch env data
  src/runners/aws_batch.js
  test/unit_tests/runners/test_aws_batch.js
Labels: size/S

#359 fix(http.js): add port to http resource name if set
  src/events/http.js
Labels: size/XS

#358 docs(readme): update mongo supported version
  README.md
Labels: size/XS

#356 fix(ioredis.js): support dy-ioredis
  src/events/ioredis.js
Labels: size/XS

#360 fix(http.js): ignore aws:443 calls
  src/helpers/http.js
Labels: size/XS

#361 feat(tracer.js): get trace url
  README.md
  src/consts.js
  src/index.d.ts
  src/index.js
  src/tracer.js
  test/unit_tests/test_tracer.js
Labels: size/M

#363 fix(lambda.js): support id propagation into response
  README.md
  src/consts.js
  src/wrappers/lambda.js
Labels: size/S

#362 fix(lambda.js): support async step function response
  src/wrappers/lambda.js
Labels: size/M

#364 feat(module_utils.js): auto finding sub node_modules folders
  README.md
  src/events/module_utils.js
Labels: size/M

#366 fix(module_utils.js): add missing node_modules in Lambda envs
  README.md
  src/consts.js
  src/events/module_utils.js
Labels: size/S

#367 fix(lambda.js): fix response alter in case of null or array
  src/wrappers/lambda.js
Labels: size/XS

#365 fix(http.js): don't capture standard ports
  src/events/http.js
Labels: size/XS

#368 fix(lambda.js): add stack trace data in trigger
  src/wrappers/lambda.js
Labels: size/XS
