Repository epsagon/epsagon-node, pull requests merged in 2020-05, with the labels that each got.

#267 fix(tracer.js): add api gateway metadata to stripfunc
  src/tracer.js
Labels: size/S

#270 fix(http): fix concurrent request data handling in http
  src/events/http.js
Labels: size/M

#273 fix(http): fix headers deprecation message
  src/events/http.js
Labels: size/XS

#274 fix(tracer.js): add api gateway body to stripApiGateway
  src/tracer.js
Labels: size/M

#275 feat(k8s): adding k8s container id
  src/containers/k8s.js
Labels: size/S

#276 fix(tracer.js): catching json stringify errors
  src/tracer.js
  src/utils.js
Labels: size/M

#278 fix(lambda_env.js): disable_epsagon env on auto-tracing
  src/wrappers/lambda_env.js
Labels: size/XS

#279 fix(lambda.js): use fail exception only if not used setError
  src/wrappers/lambda.js
Labels: size/XS

#277 feat(kafka.js): add producer connect support
  src/events/kafkajs.js
Labels: size/M

#281 ci(owners): setting team as owners
  .github/CODEOWNERS
Labels: size/XS

#282 fix(env-wrapper): handling user handler import error
  src/wrappers/lambda_env.js
Labels: size/XS

#283 feat(openwhisk.js): capture namespace and host in openwhisk
  src/events/openwhisk.js
Labels: size/XS

#285 fix(http.js): update oauth2.googleapis.com to ignored list
  src/helpers/http.js
Labels: size/XS

#286 fix(kafka.js): wrap producer send function with shimmer
  src/events/kafkajs.js
Labels: size/L

#287 fix(tracer.js): fix crashing when adding label
  src/tracer.js
Labels: size/XS

#288 fix(tracer.js): skip setError if no runner found
  src/tracer.js
Labels: size/XS

#280 feat(azure_sdk): initial support for azure sdk
  src/events/aws_sdk.js
  src/events/azure_sdk.js
  src/helpers/http.js
  src/patcher.js
Labels: size/L

#289 feat(tracer): change trace trimming function
  src/consts.js
  src/helpers/events.js
  src/tracer.js
  test/unit_tests/test_tracer.js
Labels: size/L, status: ready

#290 fix(tracer.js): change event trimming print to debugLog
  src/tracer.js
Labels: size/XS

#291 feat(aws_sdk): add kinesis putRecords support
  src/events/aws_sdk.js
Labels: size/S

#292 Adding winston logger + cw transport support
  package-lock.json
  package.json
  src/events/module_utils.js
  src/events/winston.js
  src/events/winston_cloudwatch.js
  src/patcher.js
  src/tracer.js
  test/acceptance/acceptance.js
  test/acceptance/lambda-handlers/handler_tracer_test.js
Labels: size/L

#293 fix(openwhisk.js): extract last activation id
  src/events/openwhisk.js
Labels: size/XS
