Repository epsagon/epsagon-node, pull requests merged in 2020-08, with the labels that each got.

#330 fix(vpc-timeout): added proper timeout to trace send
  src/tracer.js
Labels: size/S

#340 fix(index.js): expose consts
  src/index.js
Labels: size/XS

#341 fix(index.d.ts): update init options
  src/index.d.ts
Labels: size/XS

#342 feat(local_trace_collector): send traces to local trace collector
  src/config.js
  src/consts.js
Labels: size/XS, status: ready

#339 feat(ldap.js): support ldap.js createClient
  .gitignore
  package-lock.json
  package.json
  src/events/ldap.js
  src/patcher.js
  src/utils.js
  test/unit_tests/events/ldap-server-mock/ldap-server-mock-conf.json
  test/unit_tests/events/ldap-server-mock/users.json
  test/unit_tests/events/ldapjs.js
Labels: size/L

#343 fix(config.js): disable tracing on config set
  src/config.js
  src/tracer.js
Labels: size/S

#344 fix(package.json): update packages
  package-lock.json
Labels: size/XS

#346 fix(aws.js): add sns message attributes
  src/events/aws_sdk.js
  src/triggers/aws_lambda.js
Labels: size/XS

#345 ldap.js-documentation-update
  README.md
Labels: size/XS, status: ready

#347 fix(config): increase default timeout
  README.md
  src/config.js
Labels: size/M

#349 fix(utils.js): update debug prints with [EPSAGON]
  src/containers/azure.js
  src/utils.js
Labels: size/XS
