Repository epsagon/epsagon-node, pull requests merged in 2020-04, with the labels that each got.

#258 fix(http.js): collect openwhisk last activation ID header
  src/events/http.js
Labels: size/XS

#257 fix(http.js): add config to disable http responses capture
  src/config.js
  src/events/http.js
  src/events/http2.js
Labels: size/M

#260 fix(readme.md): update readme
  README.md
Labels: size/L

#261 fix(node.js): set runner event
  src/wrappers/node.js
  test/unit_tests/wrappers/test_node.js
Labels: size/S

#262 feat(cw logs identifier): add tracer get log identifier api
  src/event.js
  src/runners/aws_batch.js
  src/tracer.js
Labels: size/S

#264 feat(utils.js): support numeric labels
  README.md
  src/consts.js
  src/utils.js
  test/unit_tests/test_tracer.js
Labels: size/S

#263 feat(bunyan support): add bunyan logging instrumentation
  README.md
  src/config.js
  src/event.js
  src/events/bunyan.js
  src/patcher.js
  src/runners/aws_batch.js
  src/tracer.js
Labels: size/M

#265 fix(http.js): add debug prints to http request body
  src/events/aws_sdk.js
  src/events/http.js
Labels: size/S

#266 fix(http.js): add debug data to http request
  src/events/http.js
Labels: size/M
