Repository epsagon/epsagon-node, pull requests merged in 2020-12, with the labels that each got.

#394 feat(tracer): export add to pending event function
  src/tracer.js
Labels: size/S

#396 fix(google_cloud.js): fix job id extraction
  src/events/google_cloud.js
Labels: size/XS

#397 fix(aws_sdk): add eventbridge support
  src/events/aws_sdk.js
Labels: size/XS

#398 Update README with EPSAGON_ALLOW_NO_ROUTE
  README.md
Labels: size/XS

#401 fix(index.d.ts): update missing param ignoredKeys
  src/index.d.ts
Labels: size/XS

#400 feat(cassandra.js): add support for cassandra-driver
  README.md
  src/events/cassandra-driver.js
  src/patcher.js
Labels: size/L
