Repository epsagon/epsagon-node, pull requests merged in 2021-01, with the labels that each got.

#403 fix(lambda.js): catch unhandled promise rejections
  src/wrappers/lambda.js
  test/unit_tests/wrappers/test_lambda.js
Labels: size/S

#405 fix(ioredis.js): support buffers and return values
  src/events/ioredis.js
Labels: size/S

#407 fix(deps): revent bump axios from 0.19.0 to 0.21.1
  package-lock.json
  package.json
Labels: size/XS

#409 fix(lambda.js): revert catch unhandled promise rejections
  src/wrappers/lambda.js
  test/unit_tests/wrappers/test_lambda.js
Labels: size/S

#406 feat(config.js): enable batch mode by default
  README.md
  src/config.js
Labels: size/XS

#410 fix(README): Add initialization-related notes
  README.md
Labels: size/XS

#411 fix(tracer.js): accept tracer object to send
  src/consts.js
  src/events/ioredis.js
  src/tracer.js
Labels: size/S

#412 fix(http.js): support simple-oauth2 version 4
  src/events/http.js
Labels: size/XS

#413 fix(tracer.js): propagate tracer to send function
  src/tracer.js
Labels: size/S

#414 fix(cicd): hotfix - disabling auto release
  .travis.yml
Labels: size/XS

#416 feat(performance): added createdAt to the tracer
  src/tracer.js
Labels: size/XS

#417 fix(performance): improve addToMetadata performance
  src/event.js
Labels: size/S

#418 fix(tracer): optimizing filter trace
  src/config.js
  src/tracer.js
  test/unit_tests/test_tracer.js
Labels: size/M

#415 Verify existence of tracer obj
  src/tracer.js
Labels: size/XS

#420 feat(performance): added unpatch method to epsagon
  src/events/dns.js
  src/events/fs.js
  src/events/module_utils.js
  src/index.d.ts
  src/index.js
Labels: size/M

#421 feat(performance): using console.log for hammers
  .eslintrc
  src/events/module_utils.js
Labels: size/XS

#422 feat(patcher): adding patching whitelist functionality
  src/config.js
  src/patcher.js
Labels: size/L

#426 fix(simple-oauth2.js): add simple-oauth2 unit-test
  package-lock.json
  package.json
  test/unit_tests/events/oauth2-server-mock/server.js
  test/unit_tests/events/simple-oauth2.js
Labels: size/L

#427 fix(http.js): add debug prints
  src/events/http.js
Labels: size/S
