Repository epsagon/epsagon-node, pull requests merged in 2021-11, with the labels that each got.

#530 Sdk 158 sns v3
  package-lock.json
  src/events/aws_sdk_v3.js
  src/patcher.js
Labels: size/L

#532 fix(fake-commit): deploy previous pr
  README.md
Labels: size/XS

#533 fix(addnewline): add new line
  README.md
Labels: size/XS

#534 fix(awssdkv3): increasing patch scope to catch more events
  src/events/aws_sdk_v3.js
  test/acceptance/run.sh
Labels: size/S

#535 fix(tracer): add http query params
  src/events/http.js
Labels: size/XS

#537 Fix/sortify err/sdk 122
  package-lock.json
  package.json
  src/events/aws_sdk.js
  src/events/aws_sdk_v3.js
  src/triggers/aws_lambda.js
Labels: size/S

#538 fix(add-aws-sdk-v3): add test for publish sns
  package-lock.json
  package.json
  src/events/aws_sdk_v3.js
  test/unit_tests/consts.js
  test/unit_tests/events/aws_v3_test.js
Labels: size/M

#539 Revert "fix(add-aws-sdk-v3): add test for publish sns"
  package-lock.json
  package.json
  src/events/aws_sdk_v3.js
  test/unit_tests/consts.js
  test/unit_tests/events/aws_v3_test.js
Labels: size/M

#540 Fix package lock issue
  package-lock.json
  package.json
  src/events/aws_sdk_v3.js
  test/unit_tests/consts.js
  test/unit_tests/events/aws_v3.test.js
Labels: size/M

#541 fix(sns-test): change topic arn
  test/unit_tests/consts.js
Labels: size/XS
