Repository epsagon/epsagon-node, pull requests merged in 2021-03, with the labels that each got.

#459 fix(readme-batch): update batch documentation
  README.md
Labels: size/XS

#461 fix(wsk): revert finally changes of #428
  src/wrappers/openwhisk.js
Labels: size/XS

#462 fix(aws_sdk.js): update metadata fields
  src/event.js
  src/events/aws_sdk.js
Labels: size/XS

#463 fix(dynamodb-stream): add DynamoDB stream as additional data only when metadaOnly is false
  src/triggers/aws_lambda.js
Labels: size/XS

#464 fix(sqs): add total_record_count in SQS trigger lambda
  src/events/aws_sdk.js
  src/triggers/aws_lambda.js
Labels: size/S

#460 fix(kinesis): add useful info for kinesis.putRecords trace
  src/events/aws_sdk.js
  src/triggers/aws_lambda.js
Labels: size/M

#465 feat(aws_lambda.js): add support for APIGW HTTP V2
  src/triggers/aws_lambda.js
Labels: size/M
