Repository epsagon/epsagon-node, pull requests merged in 2021-06, with the labels that each got.

#491 fix(aws_lambda): fix cold start detection in provisioned concurrency functions
  src/runners/aws_lambda.js
  test/unit_tests/wrappers/test_lambda.js
Labels: size/S

#496 fix(typescript): support regex ignored keys
  .travis.yml
  src/index.d.ts
Labels: size/XS

#498 feat(sql): ignore response rows from queries to specific tables
  README.md
  src/config.js
  src/events/sql.js
  src/index.d.ts
  src/tracer.js
  test/unit_tests/test_config.js
Labels: size/L

#501 feat(logs-transport): added logs transport
  .editorconfig
  src/config.js
  src/trace_senders/http.js
  src/trace_senders/logs.js
  src/tracer.js
Labels: size/L
