Repository epsagon/epsagon-node, pull requests merged in 2021-05, with the labels that each got.

#478 feat(google_cloud_functions.js): add support for GCP function
  README.md
  src/index.d.ts
  src/index.js
  src/wrappers/google_cloud_function.js
Labels: size/L

#475 Feat(aws-sdk) add getSignedUrl support
  src/events/aws_sdk.js
  src/utils.js
Labels: size/L

#479 Feat(module_utils): Resolve Relative Module Paths
  src/events/module_utils.js
Labels: size/XS

#486 feat(ssm): added support to SSM.getParameters, SSM.getParametersByPath
  src/events/aws_sdk.js
Labels: size/M

#487 feat(neo4j): added support to Neo4j operations
  src/event.js
  src/events/mongodb.js
  src/events/neo4j.js
  src/patcher.js
Labels: size/L

#488 Revert "Feat(aws-sdk) add getSignedUrl support"
  src/events/aws_sdk.js
  src/utils.js
Labels: size/L

#489 fix(readme): change reademe file
  README.md
Labels: size/XS

#490 Update README.md
  README.md
Labels: size/XS
