Repository epsagon/epsagon-node, pull requests merged in 2021-04, with the labels that each got.

#467 fix(aws_sdk.js): support put records in kinesis
  src/events/aws_sdk.js
Labels: size/XS

#469 fix(ec2.js): ignore cases of irrelevant response
  src/containers/ec2.js
Labels: size/XS

#470 feat(aws-sdk.js): support cognito calls
  src/events/aws_sdk.js
Labels: size/M

#471 fix(release): small issue
  src/events/sql.js
Labels: size/XS

#472 fix: removing circular references before ignoring keys
  package-lock.json
  package.json
  src/tracer.js
Labels: size/XS

#473 feat: added try/catch around filterTrace call, added limit to recursion
  src/tracer.js
Labels: size/S

#474 feat(tencent): support tencent functions
  src/events/tencent-cos.js
  src/helpers/http.js
  src/index.d.ts
  src/index.js
  src/patcher.js
  src/runners/tencent_function.js
  src/triggers/tencent_function.js
  src/wrappers/tencent.js
Labels: size/XL

#476 fix(improve_loading_time): improve loading time
  src/events/aws_sdk.js
  src/events/winston_cloudwatch.js
  src/patcher.js
  src/triggers/aws_lambda.js
  test/acceptance/acceptance.js
Labels: size/M
