Repository epsagon/epsagon-node, pull requests merged in 2021-02, with the labels that each got.

#429 fix(mongo_wrap_support): change mongo wrapper to be based on shimmer
  src/events/mongodb.js
Labels: size/L

#428 fix(wsk): fix hanging openwhisk actions
  src/wrappers/openwhisk.js
Labels: size/XS

#432 fix(typescript-declaration): change labels declaration
  src/index.d.ts
Labels: size/XS

#435 fix(test-coverage): add nyc for test coverage
  .gitignore
  package-lock.json
  package.json
Labels: size/XS

#430 fix(layers): add nodejs14
  .travis.yml
  scripts/publish_layers.sh
Labels: size/XS

#438 fix(import-path): fix path
  src/events/dns.js
  src/trace_queue.js
Labels: size/XS

#439 build(readme.md): add support for fastify
  README.md
Labels: size/M

#440 docs(readme.md): update AWS Batch instructions
  README.md
Labels: size/XS

#441 fix(index.d.ts): update wrapBatchJob
  src/index.d.ts
Labels: size/XS

#444 fix(aws_sdk.js): support DDB update item hash
  src/events/aws_sdk.js
Labels: size/XS

#443 fix(typescript-example): simple example how to use TS with webpack
  examples/hello-world-typescript/package.json
  examples/hello-world-typescript/src/handler.ts
  examples/hello-world-typescript/src/queries/addSomethingQuery.ts
  examples/hello-world-typescript/tsconfig.build.json
  examples/hello-world-typescript/tsconfig.json
  examples/hello-world-typescript/webpack.config.js
Labels: size/L

#445 fix(sqs_utils.js): update sns-sqs support
  src/resource_utils/sqs_utils.js
Labels: size/XS

#446 feat(ssm): ssm getParameter support
  src/events/aws_sdk.js
Labels: size/M

#454 fix(batch-readme): update readme batch section
  README.md
Labels: size/XS

#452 fix(index.d.ts): add enable and disable functions
  src/index.d.ts
Labels: size/XS

#456 Handle uncaught exceptions and unhandled rejected promises
  src/wrappers/lambda.js
  test/unit_tests/wrappers/test_lambda.js
Labels: size/M

#458 fix(getmetricdata): add cloudwatch getMetricData event
  src/events/aws_sdk.js
Labels: size/XS

#448 fix(stepfunction): add two extra methods to track
  src/events/aws_sdk.js
Labels: size/S
