Repository epsagon/epsagon-node, pull requests merged in 2021-12, with the labels that each got.

#547 fix(sendbatch): alert user when true
  README.md
  src/config.js
  src/consts.js
  src/utils.js
Labels: size/S

#548 feat(mongodb): added support to MongoDB >= 4
  src/events/mongodb.js
Labels: size/L

#549 fix(mongodb): fixed mongo<4 callback patching
  src/events/mongodb.js
Labels: size/S

#551 Fix/fix mongo ctx extraction
  src/events/mongodb.js
Labels: size/S

#552 feat(docs): commit for version release
  README.md
Labels: size/XS

#555 fix(testing-stability): clear ci/cd for critical updates
  test/unit_tests/consts.js
  test/unit_tests/wrappers/test_lambda.js
Labels: size/L

#553 fix(kafka): added strong ids
  src/consts.js
Labels: size/XS

#557 feat(ensure-coverage): block pr if test coverage decreases
  package.json
  test/unit_tests/events/aws_v3.test.js
  test/unit_tests/wrappers/test_lambda.js
Labels: size/L
