Repository epsagon/epsagon-node, pull requests merged in 2022-06, with the labels that each got.

#592 feat: override status code with thrown error message
  README.md
  src/config.js
  src/utils.js
  src/wrappers/lambda.js
Labels: size/M

#594 feat(manual-cicd): add a manual triggered workflow
  .github/workflows/npm-publish-github-packages.yml
Labels: size/M

#595 Feat/manual cicd/sdk 618
  .github/workflows/npm-publish-github-packages.yml
Labels: size/XS

#596 fix(cicd): fix env var name
  .github/workflows/npm-publish-github-packages.yml
Labels: size/S

#599 fix(utils): status code match safer and more inclusive
  src/config.js
  src/utils.js
  test/unit_tests/test_config.js
Labels: size/M
