Repository epsagon/epsagon-node, pull requests merged in 2022-01, with the labels that each got.

#525 feat(publish_layer): specified all compatible archs
  scripts/publish_layers.sh
Labels: size/XS

#559 fix(aws_sdk.js): inject step functions ID conditionally
  src/events/aws_sdk.js
Labels: size/M

#561 Feat(AWS-SDK-V3): DynamoDB CS-148
  src/event.js
  src/events/aws_sdk_v3.js
  src/patcher.js
Labels: size/L

#562 fix(mongodb): handle get args error by checking the version
  src/events/mongodb.js
Labels: size/XS
