Repository epsagon/epsagon-node, pull requests merged in 2022-04, with the labels that each got.

#583 fix(readme): fake commit
  README.md
Labels: size/XS

#585 feat: added op + error metadata to TransactWriteItemsCommand
  src/events/aws_sdk_v3.js
Labels: size/M

#589 ci(automerge): fixed token
  .github/workflows/dependabot-auto-merge.yml
Labels: size/XS

#584 Fix http wrapper for stripe library
  src/events/http.js
Labels: size/M

#590 ci(automerge): remove workflow
  .github/workflows/dependabot-auto-merge.yml
Labels: size/S
