Repository epsagon/epsagon-node, pull requests merged in 2022-03, with the labels that each got.

#574 ci: added dependabot auto-merge github action
  .github/workflows/dependabot-auto-merge.yml
Labels: size/S

#575 feat: console patcher created
  README.md
  src/config.js
  src/events/console.js
  src/patcher.js
  src/tracer.js
Labels: size/L

#579 Revert "feat: console patcher created (#575)"
  README.md
  src/config.js
  src/events/console.js
  src/patcher.js
  src/tracer.js
Labels: size/L

#577 Fix(Typescript) : add number and boolean types to label value
  src/index.d.ts
Labels: size/XS

#576 Feat : integrate eventbridge for aws sdk v3
  src/events/aws_sdk_v3.js
Labels: size/M

#580 Feat: Patch console for labeling
  README.md
  src/config.js
  src/events/aws_sdk_v3.js
  src/events/console.js
  src/events/sql.js
  src/patcher.js
  src/tracer.js
  src/wrappers/google_cloud_function.js
  test/unit_tests/test_config.js
Labels: size/L

#581 Fix/handing stripe call version above 1.169.0/CS-174
  src/events/http.js
Labels: size/S
